baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "rgb-dendron"

#[outputs]
#home = ["HTML", "RSS", "JSON"]

[params]
disableBreadcrumb = false

[params.dendron]
rootPath = "~/Documents/dendron-brain"
vaultPath = "notes"
cacheFile = ".dendron.cache.json"
